[tool.poetry]
name = "BadgeSort"
version = "3.1.2"
description = "Generate and sort branded Shields.io badges by color"
authors = ["Chip Wolf <github@chipwolf.uk>"]
license = "MIT"
readme = "README.md"
packages = [{include = "badgesort"}]

[tool.poetry.dependencies]
python = "^3.9"
certifi = "2023.11.17"
chardet = "5.2.0"
idna = "3.10"
poetry-core = "1.9.1"
requests = "2.32.3"
simpleicons = "7.21.0"
urllib3 = "2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
